name: PHP Composer

on:
  push:
    branches: [ GitHubBuildAction ]
  pull_request:
    branches: [ GitHubBuildAction ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/phpunit@v2
      with:
        version: 5
    - uses: nanasess/setup-php@master
      with:
        php-version: '5.6'
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    # Notes:
    # The current travis script spins up a MySQL DB - which isn't required for unit testing, and for Code Sniffs.
    # - php ci/phpcs/phpcs.phar --standard=ci/phpcs CLASSES/
    # - phpunit --configuration ci/conf/travis.xml --bootstrap CLASSES/autoloader.php TESTS/
    - name: php Code Sniff
      run: php ci/phpcs/phpcs.phar --standard=ci/phpcs CLASSES/
    - name: Unit Tests
      run: phpunit --configuration ci/conf/travis.xml --bootstrap CLASSES/autoloader.php TESTS/
